version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/.github/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci: "
    assignees:
      - paul58914080
    labels:
      - ci
      - automated
